### ISSUE TITLE
World Hangs on "Building Terrain" upon world creation

### ISSUE THREAD

**Issue by gassug3** [TheFloydman/More-Mystcraft#13]
MoreMystcraft: v0.5.3

Mystcraft: v0.13.7.02

Forge: v14.23.5.2793

Minecraft: 1.12.2

Bug occurs client-side.

Log: https://pastebin.com/ctKNRW1u

Creating a new world (using superflat worldtype in this case) causes the game to hang on "Building Terrain". Reading the log shows numerous issues with MoreMystcraft, and uninstalling the mod fixes the issue. Game does not crash, but will rather stay in a frozen state until taskkilled.

Steps to reproduce:
- Create a new world in Minecraft
- Use superflat worldtype (with void preset).

Note: This cannot be reproduced by using default worldtype

Expected behavior:
Expected to have world created in less than a few seconds (usually loads in about 5 seconds, both superflat and default worlds).

I suspect this problem occurs because of the Abandoned Studies structures (I have yet to disable them in the config and then make another void world with them, and see if that works at all), since this works perfectly in normal worlds and normal superflat worlds (i.e, non-void superflat worlds).

**Comment by TheFloydman** [comment]
Alright, the fix is pretty easy. When determining where to place a library it currently gives up at y = 0, but when placing the cobblestone underneath it keeps going until it hits ground. This is, of course, a problem if it is over a void. I have updated it to stop once it hits y = 0. It will be fixed in the next release.
